@startuml Overview
' ==============================
' システム外観
' ==============================
abstract Actor
abstract PlayableActor
abstract Enemy
class Status
class ItemManager
abstract Item
class Equipment
class Consumable
abstract Location
class Town
class Dungeon
class Field

Actor <|-- PlayableActor
Actor <|-- Enemy
Actor o-- Status
PlayableActor <|-- ItemManager
ItemManager o-- Item
Item <|-- Equipment
Item <|-- Consumable
Location <|-- Town
Location <|-- Dungeon
Location <|-- Field

@enduml

@startuml Character
' ==============================
' キャラクター関連
' ==============================
abstract Actor{
	+ BaseStatus BaseStatus
	+ Vecotr2 position
	+ ItemManager inventory
	+ void move(int x, int y)
	+ void attack(Actor target)
}
class PlayableActor{}
abstract Enemy{}

' ------------------------------
' Actor
' ------------------------------
Actor "1" <|-- "*" PlayableActor
Actor "1" <|-- "*" Enemy
Actor "1" *-- "*" Status

' ------------------------------
' Enemy
' ------------------------------
Enemy <|-- Goblin
Enemy <|-- Slime
Enemy <|-- AnyOtherEnemy

@enduml

@startuml Status
' ==============================
' ステータス関連
' ==============================
abstract Actor
abstract PlayableActor

struct BaseStatus{
	int health
	int CON
	int SIZ
	int DEX
	int APP
	int INT
	int POW
	int EDU
	int LUK
	int EXP
	int XP
}
struct CombatStatus{
	int AttackPower
	int MagicPower
	int AttackResist
	int MagicResist
}
struct LifeStatus{
	int 信頼度
	int スタミナ
}
struct SexualStatus{
	int 性欲
	int えっち熟練度
	int 感度
	int 妊娠率
	int 危険日
}
struct ActivityCount{
	int 性交回数
	int プレイごとのカウント
}

' ------------------------------
' Actor
' ------------------------------
Actor "1" <|-- "*" PlayableActor
Actor "1" *-- "1" ItemManager : Itemを管理
Actor "1" *-- "1" BaseStatus : ステータスを管理
Actor "1" *-- "1" CombatStatus : 戦闘時参照
Actor "1" *-- "1" SexualStatus : えっち時やえっちイベントで参照

' ------------------------------
' PlayableActor
' ------------------------------
PlayableActor "1" *-- "1" LifeStatus
PlayableActor "1" *-- "1" ActivityCount

@enduml

@startuml Item
' ==============================
' アイテム関連
' ==============================
class ItemManager{
	+ Item[] items
	+ item[] equipments
	+ void useItem(Item item)
	+ void equip(Equipment equipment)
}
abstract Item{
	+ string name
	+ string description
	+ void use(Actor target)
}
abstract Equipment{
	+ void Remove(Equipment)
}
' 着脱機能
' 呪いの装備とかは「何もしないRemove」で実装する
abstract Weapon
abstract Armor
abstract Actor

' ------------------------------
' Item
' ------------------------------
Item "1" o-- "*" Equipment : 装備
Item "1" o-- "*" Consumable : 使用

' ------------------------------
' Equipment
' ------------------------------
Equipment "1" <|-- "*" Weapon
Equipment "1" <|-- "*" Armor

Actor "1" *-- "*" ItemManager

' ------------------------------
' ItemManagerとItem
' ------------------------------
ItemManager "1" o-- "*" Item : 所持

' ------------------------------
' Consumable
' ------------------------------
object Potion
object Food
object AnyOtherItems

Consumable <|-- Potion
Consumable <|-- Food
Consumable <|-- AnyOtherItems

@enduml

@startuml World
' ==============================
' ワールド
' ==============================
abstract Location{
	+ void loadMap()
	+ void renderMap()
}
abstract FieldObject{}
abstract Facility{}
abstract Item
abstract Enemy

' ------------------------------
' Location
' ------------------------------
Location <|-- Town
Location <|-- Dungeon
Location <|-- Field
Location *-- FieldObject
' --- Mapと他のクラス ---
Location o-- Enemy : 出現敵
Location o-- Item : フィールドアイテム

' ------------------------------
' FieldObject
' ------------------------------
object 家具
object 岩
object 罠

FieldObject <|-- FieldGimmick
FieldObject <|-- Prop
Prop -- 家具
FieldGimmick -- 岩
FieldGimmick -- 罠

' ------------------------------
' Town
' ------------------------------
Town <|-- Facility

@enduml

@startuml GameMode
' ==============================
' ゲームモード遷移
' ==============================
[*] --> StartMenu
StartMenu --> Town
StartMenu --> [*] : デスクトップに戻る

Town --> StartMenu : ゲーム終了
Town --> Adventure : 探索開始

Adventure --> Battle : 戦闘イベント発生

Battle --> Win : 戦闘に勝利
Win --> Adventure

Battle --> GameOver : 体力ゼロ

StartMenu --> Option : オプションボタン押下
Town --> Option : オプションボタン押下
Adventure --> Option : オプションボタン押下
@enduml

@startuml Talk
' ==============================
' 会話イベント遷移
' ==============================
Town --> Talk : 会話イベント発生
Talk --> Town : 会話終了
Talk --> Adventure : 会話イベント終了

Adventure --> Talk : 会話イベント発生
Adventure --> Win : 勝利
Adventure --> GameOver : 敗北

Win --> Talk : 条件を満たした場合、イベントCGに遷移

GameOver --> Talk
@enduml