@startuml
title グリッド座標系
skinparam Linetype ortho

enum Direction{
	Up,
	Down,
	Right,
	Left,
}
class GridPosition{
	+ int x
	+ int y
	+ Direction dir
	+ Translate(int x, int y) : void
	+ Rotate(Direction dir) : void
}
class Status{
	
}
class Actor{
	+ GridPosition pos
	+ Move(int x, int y) : void
}
@enduml