@startuml
title プレイヤー
skinparam Linetype ortho

' オブジェクト
class Player{
	+ Move(int,int) : void
	+ Interact() : void
}

' インタフェース
interface IMovable{
	+ Move(int,int) : void
}
interface IInteract{
	+ Interact(IIntaractable) : void
}
interface IIntaractable{
	+ GetReaction() : void
}

interface IInputHandler{
	+ Enable() : void
	+ Disable() : void
}
class PlayerInputHandler{
	- List<IInputHandler> _inputHandlers
	+ OnEnable() : void
	+ OnDisable() : void
}
class MoveInputHandler{
	+ InputAction
}

' 関係
IMovable <|-- Player : 実装
IMovable <- PlayerInputHandler : 利用
MonoBehavior <|-- InputHandlerComponent : 継承
InputHandlerComponent --> IInputHandler : 利用
IInputHandler <|-- PlayerInputHandler : 実装
IInputHandler <|-- MenuInputHandler : 実装

@enduml